[language-server.glsl_analyzer]
command = "glsl_analyzer"

[[language]]
name = "glsl"
language-servers = [ "glsl_analyzer" ]

[language-server.rust-analyzer.config]
cargo.target = "wasm32-unknown-unknown"
